; LHC CLI Installation Settings for SkillzLink Docker

[db]
host = mysql
user = skillzlink
password = skillzlink
database = skillzlink
port = 3306

[admin]
AdminUsername = admin
AdminPassword = admin123
AdminEmail = admin@skillzlink.local
AdminName = SkillzLink
AdminSurname = Admin
Domain = localhost
DefaultDepartament = Support
ForceVirtualHost = 0
Extensions =
ApacheUserGroupName = www-data
ApacheUserName = www-data
TimeZone = Africa/Johannesburg
WebhooksEnabled = 0
WebhooksWorker = http
DefaultConfigs = []
